### ISSUE TITLE
Error when using DuckDNS: TypeError: __init__() takes at least 4 arguments (3 given)

### ISSUE THREAD

**Issue by Warudo** [infothrill/python-dyndnsc#58]
When trying to sue DuckDNS, I get the following error:
```
2016-08-28 00:38:59,403 DEBUG ArgumentParser(prog='dyndnsc', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
2016-08-28 00:38:59,404 DEBUG Attempting to read configuration from ['/usr/lib/python2.7/site-packages/dyndnsc/resources/presets.ini', 'dyndnsc.cfg']
2016-08-28 00:38:59,407 DEBUG Successfully read configuration from ['/usr/lib/python2.7/site-packages/dyndnsc/resources/presets.ini', 'dyndnsc.cfg']
2016-08-28 00:38:59,408 DEBUG config file sections: ['preset:no-ip.com', 'preset:freedns.afraid.com', 'preset:nsupdate.info:ipv4', 'preset:nsupdate.info:ipv6', 'preset:dns.he.net', 'preset:dnsimple.com', 'preset:dnsdynamic.org', 'preset:hopper.pw:ipv4', 'preset:hopper.pw:ipv6', 'preset:dyn.com', 'preset:duckdns.org', 'dyndnsc', 'duckdns_ipv4']
2016-08-28 00:38:59,408 DEBUG raw config for 'duckdns_ipv4': {'detector-iface': 'ppp0', 'updater-password': '[removed]', 'use_preset': 'duckdns.org', 'updater': 'duckdns', 'detector-iface-family': 'INET4', 'detector': 'iface', 'updater-hostname': '[removed]', 'updater-url': 'https://www.duckdns.org/update'}
2016-08-28 00:38:59,408 DEBUG Available plugins: []
2016-08-28 00:38:59,409 DEBUG Enabled plugins: []
2016-08-28 00:38:59,409 DEBUG collected_configs: {'duckdns_ipv4': {'detector': [('iface', {'iface': 'ppp0', 'iface-family': 'INET4'})], 'updater': [('duckdns', {'url': 'https://www.duckdns.org/update', 'password': '[removed]', 'hostname': '[removed]'})]}}
2016-08-28 00:38:59,409 DEBUG Initializing client for 'duckdns_ipv4'
Traceback (most recent call last):
  File "/usr/bin/dyndnsc", line 11, in <module>
    load_entry_point('dyndnsc==0.4.2', 'console_scripts', 'dyndnsc')()
  File "/usr/lib/python2.7/site-packages/dyndnsc/cli.py", line 144, in main
    collected_configs[thisconfig], plugins=plugins)
  File "/usr/lib/python2.7/site-packages/dyndnsc/core.py", line 182, in getDynDnsClientForConfig
    initparams['updater'] = get_updater_class(updater_name)(**updater_options)
TypeError: __init__() takes at least 4 arguments (3 given)
```
My config file:
```
[dyndnsc]
configs = duckdns_ipv4

[duckdns_ipv4]
use_preset = duckdns.org
updater-hostname = [removed]
updater-password = [removed]
detector = iface
detector-iface = ppp0
detector-iface-family = INET4
```

**Comment by ThomasWaldmann** [comment]
Don't sue them. :)

**Comment by infothrill** [comment]
dyndnsc --help

               [--updater-duckdns-hostname UPDATER_DUCKDNS_HOSTNAME]
               [--updater-duckdns-token UPDATER_DUCKDNS_TOKEN]
               [--updater-duckdns-url UPDATER_DUCKDNS_URL]

I.e. the parameter in the config file should be "updater-token" and not "updater-password"
