### ISSUE TITLE
No class named 'webcheck4' could be found

### ISSUE THREAD

**Issue by Erik8219** [infothrill/python-dyndnsc#84]
Hey Ho

when i try to run    dyndnsc --config dyndnsc.conf
I get the follwoing error

Traceback (most recent call last):
  File "/usr/local/bin/dyndnsc", line 11, in <module>
    load_entry_point('dyndnsc==0.5.dev0', 'console_scripts', 'dyndnsc')()
  File "/usr/local/lib/python2.7/dist-packages/dyndnsc-0.5.dev0-py2.7.egg/dyndnsc/cli.py", line 171, in main
    collected_configs[thisconfig], plugins=plugins)
  File "/usr/local/lib/python2.7/dist-packages/dyndnsc-0.5.dev0-py2.7.egg/dyndnsc/core.py", line 184, in getDynDnsClientForConfig
    klass = get_detector_class(detector_name)
  File "/usr/local/lib/python2.7/dist-packages/dyndnsc-0.5.dev0-py2.7.egg/dyndnsc/detector/manager.py", line 16, in get_detector_class
    return find_class(name, detector_classes())
  File "/usr/local/lib/python2.7/dist-packages/dyndnsc-0.5.dev0-py2.7.egg/dyndnsc/common/load.py", line 32, in find_class
    raise ValueError("No class named '%s' could be found" % name)
ValueError: No class named 'webcheck4' could be found

I installed dyndnsc fresh from repo. Can anybody tell me whats wrong?

**Comment by infothrill** [comment]
this seems to be a bug introduced with commit https://github.com/infothrill/python-dyndnsc/commit/c4f5d234c1844e4dd6e17dd9705364dd497b2343

**Comment by infothrill** [comment]
@Erik8219 Please update your code, the issue should be gone now.

**Comment by Erik8219** [comment]
That was fast. Thank you. Works for me.
